### PR TITLE
Simplify the method of setting permissions on the private key

### PR DESCRIPTION
**Pull request by luipugs**
~The previous trigger is just a string constant. It would run during the
first apply but would be skipped when terraform is applied again because
there was no change to the trigger. This changes the trigger to the
SHA256 hash of the private key so that chmod will be rerun when the file
is recreated.~

Instead of running an external command, use terraform's built in way of setting permissions on local file resources.

### CODE REVIEW

**Comment by aknysh** [comment]
@luipugs  thanks for the PR! (and nice find).
Please address the error:

```TestExamplesComplete 2019-12-18T21:07:58Z command.go:121: Error: Error in function call                                                                          
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:                                                                                                        
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:   on ../../main.tf line 64, in resource "null_resource" "chmod":                                       
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:   64:     local_file_private_key_pem = filesha256(local.private_key_filename)                          
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:     |----------------                                                                                  
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:     | local.private_key_filename is "/secrets/eg-test-aws-key-pair"                                    
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:                                                                                                        
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121: Call to function "filesha256" failed: no file exists at                                                
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121: /secrets/eg-test-aws-key-pair.                                                                         
TestExamplesComplete 2019-12-18T21:07:58Z command.go:121:                                                                                                        ```

CI?CD test is failing https://g.codefresh.io/public/accounts/cloudposse/builds/5dfa949db335087be679ead5

**Comment by luipugs** [comment]
Changed the method of setting the permissions.

**Pull request merged**
