### PR TITLE
do not show private key content

### PR DESCRIPTION
**Pull request by etwillbefine**

### CODE REVIEW

**Comment by etwillbefine** [comment]
is there a way to get this merged to avoid showing private key in terraform diffs?

**Comment by etwillbefine** [comment]
Sorry but there a different problems with that.

First I'm not able to regenerate the docs when using the 3 commands provided without installing gomplate locally with brew. 

<details>
<summary>Error output</summary>
<p>
➜  terraform-aws-key-pair git:(master) make init
Cloning https://github.com/cloudposse/build-harness.git#master...
Cloning into 'build-harness'...
remote: Enumerating objects: 1199, done.
remote: Total 1199 (delta 0), reused 0 (delta 0), pack-reused 1199
Receiving objects: 100% (1199/1199), 292.40 KiB | 1.00 MiB/s, done.
Resolving deltas: 100% (639/639), done.
➜  terraform-aws-key-pair git:(master) make readme/deps
makInstalling packages 0.95.0...
Cloning into '/Users/tim/work/contrib/terraform-aws-key-pair/build-harness/vendor/packages'...
e readme
remote: Enumerating objects: 293, done.
remote: Counting objects: 100% (293/293), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 293 (delta 52), reused 245 (delta 43), pack-reused 0
Receiving objects: 100% (293/293), 52.60 KiB | 555.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
curl --retry 3 --retry-delay 5 --fail -sSL -o /Users/tim/work/contrib/terraform-aws-key-pair/build-harness/vendor/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.1.0/gomplate_darwin-amd64-slim && chmod +x /Users/tim/work/contrib/terraform-aws-key-pair/build-harness/vendor/gomplate
➜  terraform-aws-key-pair git:(master) make readme
curl --retry 3 --retry-delay 5 --fail -sSL -o /Users/tim/work/contrib/terraform-aws-key-pair/build-harness/vendor/terraform-docs https://github.com/segmentio/terraform-docs/releases/download/v0.4.5/terraform-docs-v0.4.5-darwin-amd64 && chmod +x /Users/tim/work/contrib/terraform-aws-key-pair/build-harness/vendor/terraform-docs
make: gomplate: No such file or directory
make: *** [readme/build] Error 1
➜  terraform-aws-key-pair git:(master) make readme/deps
Package gomplate already installed
➜  terraform-aws-key-pair git:(master) make readme
Package terraform-docs already installed
make: gomplate: No such file or directory
make: *** [readme/build] Error 1
</p>
</details>

Second when I install gomplate locally to execute `make readme` nothing changes with the following output "Generated README.md from /Users/tim/work/contrib/terraform-aws-key-pair/build-harness/templates/README.md.gotmpl using data from /Users/tim/work/contrib/terraform-aws-key-pair/build-harness/templates/README.yaml" and I have no changes to commit or new commits in the log.

Are there maybe no README changes required or cannot be detected?

**Comment by aalimovs** [comment]
@aknysh looks like no README changes are required, would be great to merge this in.

**Comment by etwillbefine** [comment]
Thanks for merging 👍

**Pull request merged**
